### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by asimilon** [eclipseeer/circlarc.svg#2]
I was looking to use the code at https://github.com/eclipseeer/circlarc.svg/blob/master/src/logic/getCurveApproximateCircle.js in a desktop project UI, but there is no license.

It says "open source", but that could mean GPL or something more flexible like MIT.

In the end I've found a solution that uses SVG arcs, but I think it would be good to add an explicit license to the repo.

**Comment by eclipseeer** [comment]
you could use this code in whatever you like. What sort of license would fit your needs?

**Comment by asimilon** [comment]
Any "non-viral" license would have worked for me.  I understand why some people like GPL or other "viral" licenses, but for most of the software I work on that's not an option.
